[package]
name = "game"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy-inspector-egui = { version = "0.25", optional = true }
bevy_asset_loader = { version = "0.21", features = [
  "progress_tracking",
  "standard_dynamic_assets",
] }
macros = { path = "../macros" }
bevy_tweening = "0.11.0"
crossbeam-channel = "0.5.11"
iyes_progress = { version = "0.12.0", features = ["assets"] }
rand = "0.8.5"
wasm-bindgen = "0.2"
web-sys = "0.3"
shared = { workspace = true }
im = "15.1.0"
serde = "1.0.204"
serde_json = "1.0.120"
anyhow = "1.0.86"
bevy_kira_audio = { version = "0.20.0", features = ["ogg"] }


[dependencies.bevy]
version = "0.14"
default-features = false
features = [
  "android_shared_stdcxx",
  "animation",
  "bevy_asset",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_gilrs",
  "bevy_gizmos",
  "bevy_gltf",
  "bevy_pbr",
  "bevy_render",
  "bevy_scene",
  "bevy_sprite",
  "bevy_state",
  "bevy_text",
  "bevy_ui",
  "bevy_winit",
  "default_font",
  "hdr",
  "multi_threaded",
  "png",
  "smaa_luts",
  "sysinfo_plugin",
  "tonemapping_luts",
  "webgpu",
  "x11",
]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tungstenite = { version = "0.23.0", features = ["rustls"] }

[features]
debug = ["dep:bevy-inspector-egui"]
