[package]
name = "game"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = { version = "0.14", features = ["webgpu"] }
bevy-inspector-egui = { version = "0.25", optional = true }
bevy_asset_loader = { version = "0.21", features = [
  "progress_tracking",
  "standard_dynamic_assets",
] }
macros = { path = "../macros" }
bevy_tweening = "0.11.0"
crossbeam-channel = "0.5.11"
iyes_progress = { version = "0.12.0", features = ["assets"] }
rand = "0.8.5"
wasm-bindgen = "0.2"
web-sys = "0.3"
shared = { workspace = true }
im = "15.1.0"
serde = "1.0.204"
serde_json = "1.0.120"
tungstenite = { version = "0.23.0", optional = true, features = ["rustls"] }
anyhow = "1.0.86"


[features]
default = ["bevy/dynamic_linking", "dep:tungstenite"]
debug = ["dep:bevy-inspector-egui"]
