name = "deep-space-derby"
compatibility_date = "2024-12-10"
main = "./site/_worker.js"

[limits]
cpu_ms = 200

[durable_objects]
bindings = [{ name = "GAME", class_name = "Game" }]

[[routes]]
pattern = "dsdtv.app"
custom_domain = true

[assets]
directory = "./site/"

[observability.logs]
enabled = true


[[migrations]]
tag = "v1"
new_classes = ["Game"]
