[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.89"
worker = { git = 'https://github.com/DylanRJohnston/workers-rs.git' }

[profile.release]
lot = true
strip = true
codegen-units = 1