[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
im = "15.1.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rand = "0.8.5"
serde = "1.0.197"
serde_json = "1.0.114"
uuid = "1.7.0"
